const APP_ROUTES = {
  account: "/settings-account",
  addMeeting: "/addMeeting",
  callHistory: "/call-history",
  clientSettings: "/client-settings",
  clients: "/clients",
  company: "/company",
  dashboard: "/dashboard",
  dayOff: "/settings-dayOff",
  editTeamUser: "/team-users",
  fields: "/fields",
  forgetPassword: "/forgetPassword",
  home: "/",
  integrations: "/integrations",
  integrationSetting: "/integration-setting",
  integrationHistory: "/integrationhistory",
  leads: "/leads",
  leadsDetails: "/leadsDetails",
  login: "/login",
  meetingSettings: "/meeting-settings",
  meetings: "/meetings",
  notFound: "/404",
  numbers: "/numbers",
  publicHolidays: "/publicHolidays",
  purchaseNumber: "/purchase-number",
  purchaseNumberSetting: "/purchaseNumberSetting",
  reporting: "/reporting",
  schedule: "/settings-schedule",
  scheduleCall: "/scheduleCall",
  scheduleCallSettings: "/settings-schedule-calls",
  scheduledCalls: "/scheduled-calls",
  setPassword: "/setpassword",
  tagAndStatuses: "/tagsAndStatuses",
  tagsAndStatuses: "/tags-statuses",
  teamSchedule: "/team-schedule",
  teamSettings: "/team-settings",
  teams: "/teams",
  userAccount: "/useraccount",
  userDaysOff: "/userdaysoff",
  userSchedule: "/userschedule",
  users: "/users",
  PvNumberSettings: "/PvNumberSettings",
};

export default APP_ROUTES;
